steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/scholarsyncaibackend/scholarsyncaibackend', '-f', 'Dockerfile', '.']
  dir: 'backend'

images: 
- 'gcr.io/scholarsyncaibackend/scholarsyncaibackend' 

options:
  logging: CLOUD_LOGGING_ONLY